from django.urls import path
from main.views import *
urlpatterns=[
   path('',homefn),
   path('dashboard/',dashboardfn),
   path('feedback/', feedbackfn, name='feedback'),
   path('add/<str:t_name>',addfn,name='profile'),
   path('jobs/<int:e_id>/edit/', editfn, name='editjob'),
   path('jobs/',jobfn),
   path('delete/<int:j_id>',deletefn,name='job_delete'),
   path('jobsearch/',jobsearchfn),
   path('job/<int:job_id>/', job_detail_fn, name='job_detail'),
   path('registerinterviewer/',registerfn),
   path('registerapplicant/',registerfn),
   path('application/<int:job_id>',applicationfn,name='apply_job'),
   path('candidates/<int:job_id>/',candidatefn,name='job_candidates'),
   path('applications/<int:application_id>/status/', application_statusfn, name='application_status'),
   path('candidates/<int:job_id>/reject-selected/', bulk_reject_applications_fn, name='bulk_reject_applications'),
   path('applications/<int:application_id>/resume/', applicant_resume_fn, name='applicant_resume'),
   path('login/',loginfn),
   path('logout/',logoutfn),
   path('experiance/',experiancefn,name='experiance'),
   path('education/',educationfn,name='education'),
   path('skills/',skillfn,name='skills'),
   # path('summary/',summaryfn,name='summary'),
   path('interest/',interestfn,name='interest'),
   path('resumes/',resumesfn),
   path('resume1/',resume1fn,name='preview1'),
   path('resume2/',resume2fn,name='preview2'),
   path('resume3/',resume3fn,name='preview3'),
   path('photo/',photofn,name='photo'),
   path('expertise/',expertisefn,name='expertise'),
   path('finish/',finishfn),
   path('resume/pdf/', resume_pdf, name='resume_pdf'),
]