# Generated by Django 6.0.8 on 2026-08-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='profile',
        ),
    ]
