# Generated by Django 6.0.8 on 2026-08-22 03:46

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_resume_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='phoneno',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('others', 'Others'), ('prefer not to say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender (Optional)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('empty', 'Empty')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle name (Optional)'),
        ),
        migrations.AddField(
            model_name='resume',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
