# Generated by Django 6.0.8 on 2026-08-22 04:12

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phoneno_resume_phone_remove_resume_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='DOB (Optional)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('empty', 'Empty')], max_length=15, null=True, verbose_name='Maritul Status (Optional)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Nationality (Optional)'),
        ),
    ]
