# Generated by Django 6.0.8 on 2026-08-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resume_dob_alter_resume_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
