# Generated by Django 6.0.8 on 2026-08-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_resume_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pin_code',
            field=models.CharField(blank=True, null=True, verbose_name=' Pin code(Optional)'),
        ),
    ]
