# Generated by Django 6.0.8 on 2026-08-22 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_resume_pin_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin code (Optional)'),
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('select_a_degree', models.CharField(blank=True, choices=[('', 'Select'), ('high_school_diploma', 'High School Diploma'), ('ssc', 'Senior Secondary School Certificate (SSCE)'), ('gcse', 'General Certificate of Secondary Education (GCSEs)'), ('ged', 'GED'), ('diploma', 'Diploma'), ('national_diploma', 'National Diploma'), ('higher_national_diploma', 'Higher National Diploma'), ('post_secondary_vocational', 'Post-secondary (Technical & Vocational)'), ('associate_arts', 'Associate of Arts'), ('associate_science', 'Associate of Science'), ('associate_applied_science', 'Associate of Applied Science'), ('bachelor_arts', 'Bachelor of Arts (BA)'), ('bachelor_science', 'Bachelor of Science (BSc)'), ('bachelor_technology', 'Bachelor of Technology (B.Tech)'), ('bachelor_engineering', 'Bachelor of Engineering (BE)'), ('bachelor_commerce', 'Bachelor of Commerce (B.Com)'), ('bachelor_business_admin', 'Bachelor of Business Administration (BBA)'), ('bachelor_computer_apps', 'Bachelor of Computer Applications (BCA)'), ('llb', 'Bachelor of Laws (LLB)'), ('mbbs', 'Bachelor of Medicine, Bachelor of Surgery (MBBS)'), ('master_arts', 'Master of Arts (MA)'), ('master_science', 'Master of Science (MSc)'), ('master_technology', 'Master of Technology (M.Tech)'), ('master_business_admin', 'Master of Business Administration (MBA)'), ('master_computer_apps', 'Master of Computer Applications (MCA)'), ('master_commerce', 'Master of Commerce (M.Com)'), ('llm', 'Master of Laws (LLM)'), ('phd', 'Doctor of Philosophy (PhD)'), ('md', 'Doctor of Medicine (MD)'), ('certificate', 'Certificate Course'), ('other', 'Other')], max_length=100, null=True)),
                ('field_of_study', models.CharField(max_length=100)),
                ('graduation_start_date', models.DateField(blank=True, null=True)),
                ('graduation_end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='experiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience',
            },
        ),
    ]
