# Generated by Django 6.0.8 on 2026-08-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_resume_email_alter_resume_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('men', 'Men'), ('women', 'Women'), ('others', 'Others'), ('prefer not to say', 'Prefer not to say')], max_length=20, null=True, verbose_name='Gender (Optional)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('empty', 'Empty')], max_length=15, null=True, verbose_name='Maritul Status (Optional)'),
        ),
    ]
