# Generated by Django 6.0.8 on 2026-08-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='sk',
            new_name='skill',
        ),
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=15, null=True),
        ),
    ]
