# Generated by Django 6.0.8 on 2026-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photoup',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='Upload cv photo'),
        ),
    ]
