# Generated by Django 6.0.8 on 2026-08-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_photo_photoup'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
