# Generated by Django 6.0.8 on 2026-08-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_usercat'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercat',
            name='company_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
