# Generated by Django 6.0.8 on 2026-09-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='availability',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], max_length=20, null=True),
        ),
    ]
