# Generated by Django 6.0.8 on 2026-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_job_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='availability',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('fulltime', 'Full-time'), ('parttime', 'Part-time')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
