# Generated by Django 6.0.8 on 2026-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_job_availability_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
