# Generated by Django 6.0.8 on 2026-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_userprofile_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
