# Generated by Django 6.0.8 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_application_match_score_application_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(
                choices=[
                    ('applied', 'Applied'),
                    ('shortlisted', 'Shortlisted'),
                    ('rejected', 'Rejected'),
                    ('accepted', 'Accepted'),
                ],
                default='applied',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_template',
            field=models.CharField(
                blank=True,
                choices=[
                    ('professional1', 'Professional 1'),
                    ('professional2', 'Professional 2'),
                    ('professional3', 'Professional 3'),
                ],
                default='',
                max_length=20,
            ),
        ),
    ]
